<%@ Page Title="Edit" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Edit.aspx.cs" Inherits="DebateTeamManagementSystem.Edit" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2><%: Title %></h2>
    <h3>Edit Team Info: </h3>
    <div class="jumbotron"><asp:GridView runat="server" ID="teamsGrid"
        ItemType="DebateTeamManagementSystem.Models.Team" DataKeyNames="TeamID" 
        SelectMethod="teamsGrid_GetData"
        UpdateMethod="teamsGrid_UpdateItem"
        DeleteMethod="teamsGrid_DeleteItem"
        AutoGenerateEditButton="true"
        AutoGenerateDeleteButton="true"
        AutoGenerateColumns="false">
        <Columns>
            <asp:DynamicField DataField="TeamName" />
        </Columns>
    </asp:GridView></div>
</asp:Content>
